name: phonetowers
description: Aus Phone Towers

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.8.19+78

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0
  cupertino_icons: ^1.0.8
  #http: ^1.0.0
  dio: ^5.7.0
  logger: ^2.5.0
  permission_handler: ^12.0.1
  geohash:
    git: https://github.com/bradrushworth/dart-geohash.git
    #path: ../geohash
  location: ^8.0.1
  json_annotation: ^4.9.0
  intl: ^0.20.1
  html_unescape: ^2.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  path_provider: ^2.1.5
  #path: ^1.9.1
  firebase_analytics: ^12.0.1
  firebase_crashlytics: ^5.0.1
  in_app_purchase: ^3.2.0
  #590 was merged and update_version branch of https://github.com/jjliu15/googleads-mobile-flutter-1 has been deleted. So, current workaround is here:
  google_mobile_ads: ^7.0.0
  #    git:
#      url: https://github.com/googleads/googleads-mobile-flutter
#      ref: 356875362ddb2ac2e0056385d2729c093722fb8d
#      path: packages/google_mobile_ads
  #gma_mediation_meta: ^1.5.0 # Needs upgrade for gradle
  after_layout: ^1.2.0
  in_app_review: ^2.0.10
  app_tracking_transparency: ^2.0.6+1
  auto_size_text: ^3.0.0
  #google_map_polyutil: ^1.0.1
  #flt_telephony_info: ^0.1.3
  #dart_numerics: ^0.0.6
  #launch_review: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.2 # Causes some dependency conflicts
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  #json_serializable: ^6.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons_web/
    - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appicon.png"
  remove_alpha_ios: true
  #adaptive_icon_background: "#ffffff"
  #adaptive_icon_foreground: "assets/ItunesArtwork@2x.png"
